### ISSUE TITLE
tested by me: all ok

### ISSUE THREAD

**Issue by HerveF2** [krzysk1/swiss_vfr#1]
Hello,

I just finish flying over all the obstacles.... For me, all is ok: only uetliberg is a little "small", but anyway it is not important, because it is already included in Switzerland DLC by IPACS. Compliments ! For me, you can release, but don't forget to write that IPACS Switzerland DLC is required.

**Comment by krzysk1** [comment]
there is not uetliberg TV tower but small Uetliberg Lookout Tower close the main one. 
The TV tower is already in DLC so I didn't realized it
'IPACS Switzerland DLC is required' was added

Ray mentioned that  Blosenberg Tower does not show up. I'll check it

**Comment by HerveF2** [comment]
Yep ! I confirm: Blosenberg not shown....

**Comment by krzysk1** [comment]
Blosenberg tower fixed
